sonar.projectKey=yolo-labz_wa
sonar.projectName=wa
sonar.projectVersion=0.0.3

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,cmd/**,specs/**,docs/**,.github/**,.specify/**,internal/adapters/secondary/memory/**,internal/app/porttest/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**

# Go
sonar.go.coverage.reportPaths=cover.out

# Encoding
sonar.sourceEncoding=UTF-8
