// Package slogaudit implements the app.AuditLog port as a JSON-line
// append-only log file backed by slog.JSONHandler. Each Record call is
// synchronous and mutex-guarded; out-of-order writes (based on
// AuditEvent.TS) are rejected.
package slogaudit

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/yolo-labz/wa/v2/internal/domain"
)

// ErrOutOfOrder is returned by Record when the event timestamp is not
// strictly after the last recorded event.
var ErrOutOfOrder = errors.New("slogaudit: out-of-order timestamp")

// Audit implements the app.AuditLog port. It writes JSON lines to an
// append-only file, one line per Record call.
//
// Spec 016 FR-015 / T053: every line is stamped with
// `,"prev":"<prev_hmac>","hmac":"<this_hmac>"` before the closing `}`
// so the file is a tamper-evident hash chain. The HMAC key is loaded /
// generated by loadOrCreateKey from a sibling file (`<path>.key`,
// mode 0600) so daemon restarts continue an existing chain. Verifying
// the chain is `slogaudit.VerifyChain`.
type Audit struct {
	handler slog.Handler // Codex review §MAJOR (4): Handle errors propagate; Logger.Info swallows them
	file    *os.File
	path    string
	keyPath string
	chain   *hmacChainWriter
	mu      sync.Mutex
	lastTS  time.Time
}

// Open creates (or opens) the audit log at path. The parent directory
// is created with mode 0700; the file is opened O_APPEND|O_CREATE|O_WRONLY
// with mode 0600. An HMAC chain key is loaded from `<path>.key` (or
// generated on first use) so every Record line is tamper-evident.
func Open(path string) (*Audit, error) {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("slogaudit: mkdir %s: %w", dir, err)
	}
	keyPath := path + ".key"
	key, err := loadOrCreateKey(keyPath)
	if err != nil {
		return nil, err
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600) //nolint:gosec // path from XDG state dir, validated at startup
	if err != nil {
		return nil, fmt.Errorf("slogaudit: open %s: %w", path, err)
	}
	last, err := tailLastHMAC(path)
	if err != nil {
		_ = f.Close()
		return nil, fmt.Errorf("slogaudit: read tail %s: %w", path, err)
	}
	chain := &hmacChainWriter{f: f, key: key, last: last}
	h := slog.NewJSONHandler(chain, &slog.HandlerOptions{Level: slog.LevelInfo})
	return &Audit{
		handler: h,
		file:    f,
		path:    path,
		keyPath: keyPath,
		chain:   chain,
	}, nil
}

// KeyPath returns the path to the HMAC chain key sibling file. Used by
// `wa audit verify` to load the key without prompting the operator.
func (a *Audit) KeyPath() string { return a.keyPath }

// Path returns the audit log path the store was opened against.
func (a *Audit) Path() string { return a.path }

// Rotate atomically swaps the live audit log for a new empty file
// (FR-038). The current file is renamed to `<path>.YYYYMMDD-HHMMSS`
// (UTC), and a new file is opened at `path` with mode 0600. The
// returned rotatedPath is the old filename so callers can print or
// index it. Rotate holds the same mutex as Record, so no entries are
// lost in the swap.
func (a *Audit) Rotate() (rotatedPath string, err error) {
	a.mu.Lock()
	defer a.mu.Unlock()

	if a.file == nil {
		return "", fmt.Errorf("slogaudit: rotate: file not open")
	}

	ts := time.Now().UTC().Format("20060102-150405")
	rotated := a.path + "." + ts

	if err := a.file.Close(); err != nil {
		return "", fmt.Errorf("slogaudit: rotate: close current: %w", err)
	}
	if err := os.Rename(a.path, rotated); err != nil {
		// Reopen original so we don't lose the writer on rename failure.
		f, reopenErr := os.OpenFile(a.path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
		if reopenErr == nil {
			a.file = f
			a.chain = &hmacChainWriter{f: f, key: a.chain.key, last: a.chain.last}
			a.handler = slog.NewJSONHandler(a.chain, &slog.HandlerOptions{Level: slog.LevelInfo})
		}
		return "", fmt.Errorf("slogaudit: rotate: rename %s: %w", a.path, err)
	}

	f, err := os.OpenFile(a.path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return rotated, fmt.Errorf("slogaudit: rotate: open new: %w", err)
	}
	a.file = f
	// Spec 016 T053: rotation starts a NEW chain. The rotated file is
	// frozen with its own self-contained chain ending at the last
	// pre-rotate hmac; the new file begins fresh. Verifiers walk one
	// file at a time, so chain continuity per-file is what matters.
	a.chain = &hmacChainWriter{f: f, key: a.chain.key, last: ""}
	a.handler = slog.NewJSONHandler(a.chain, &slog.HandlerOptions{Level: slog.LevelInfo})
	a.lastTS = time.Time{}
	return rotated, nil
}

// tailLastHMAC reads the last line of the audit log and extracts its
// `hmac` field so a daemon restart picks up the chain where it left
// off. Returns "" if the file is empty, missing, or the last line has
// no hmac suffix (pre-T053 history). Errors only on read failure.
//
// Codex review §MAJOR (5): rejects partial / truncated tails. A file
// without a trailing newline indicates a mid-line crash; a line that
// does not end with the T053 `,"prev":"...","hmac":"..."}` suffix
// triggers a fresh chain. Re-seeding from unauthenticated bytes is
// strictly forbidden — an attacker who can induce mid-line truncation
// would otherwise reset the chain to a known prefix.
func tailLastHMAC(path string) (string, error) {
	buf, from, err := readTail(path)
	if err != nil || len(buf) == 0 {
		return "", err
	}
	lastLine, ok := extractLastCompleteLine(buf, from)
	if !ok {
		return "", nil
	}
	return parseChainHMACFromLine(lastLine), nil
}

// readTail returns the last <=8 KiB of path plus the byte offset that
// segment starts at, or (nil, 0, nil) for missing/empty files.
func readTail(path string) ([]byte, int64, error) {
	f, err := os.Open(path) //nolint:gosec // path from caller
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, 0, nil
		}
		return nil, 0, err
	}
	defer func() { _ = f.Close() }()

	st, err := f.Stat()
	if err != nil {
		return nil, 0, err
	}
	if st.Size() == 0 {
		return nil, 0, nil
	}
	const tailBytes = 8192
	from := int64(0)
	if st.Size() > tailBytes {
		from = st.Size() - tailBytes
	}
	if _, err := f.Seek(from, 0); err != nil {
		return nil, 0, err
	}
	buf := make([]byte, st.Size()-from)
	if _, err := f.Read(buf); err != nil {
		return nil, 0, err
	}
	return buf, from, nil
}

// extractLastCompleteLine isolates the file's final line if it is
// fully present in the tail window AND ends with `}\n`. Returns
// (line, false) when the tail is partial or the window cannot prove
// the line is complete (e.g. no embedded newline and the window did
// not start at offset 0).
func extractLastCompleteLine(buf []byte, from int64) ([]byte, bool) {
	if len(buf) == 0 || buf[len(buf)-1] != '\n' {
		return nil, false
	}
	body := buf[:len(buf)-1]
	lastNL := -1
	for i := len(body) - 1; i >= 0; i-- {
		if body[i] == '\n' {
			lastNL = i
			break
		}
	}
	var line []byte
	if lastNL < 0 {
		if from != 0 {
			return nil, false
		}
		line = body
	} else {
		line = body[lastNL+1:]
	}
	if len(line) == 0 || line[len(line)-1] != '}' {
		return nil, false
	}
	return line, true
}

// parseChainHMACFromLine extracts the recorded `hmac` from a known-
// complete T053 line. Returns "" on pre-T053 / malformed lines so the
// chain restarts from genesis.
func parseChainHMACFromLine(line []byte) string {
	prevTag := []byte(`,"prev":"`)
	idx := lastIndex(line, prevTag)
	if idx < 0 {
		return ""
	}
	tail := line[idx : len(line)-1]
	_, mac, err := parsePrevHmacTail(tail)
	if err != nil {
		return ""
	}
	return mac
}

// bytesSplit / lastIndex are inlined here to keep audit.go's bytes/strings
// import surface unchanged. The chain.go file already imports bytes; this
// file deliberately avoids the import to keep the diff small.
func bytesSplit(s []byte, sep byte) [][]byte {
	var out [][]byte
	start := 0
	for i := range s {
		if s[i] == sep {
			out = append(out, s[start:i])
			start = i + 1
		}
	}
	out = append(out, s[start:])
	return out
}

func lastIndex(s, sub []byte) int {
	if len(sub) == 0 {
		return len(s)
	}
	for i := len(s) - len(sub); i >= 0; i-- {
		match := true
		for j := range sub {
			if s[i+j] != sub[j] {
				match = false
				break
			}
		}
		if match {
			return i
		}
	}
	return -1
}

// Record writes a single audit event as a JSON line. It rejects events
// whose TS is not strictly after the last recorded event's TS.
//
// Codex review §MAJOR (4): Record now invokes handler.Handle directly
// rather than slog.Logger.Info, so a Write error from the chain writer
// (disk full, mid-line interruption) propagates back to the caller and
// lastTS is NOT advanced. Without this, slog.Logger.Info would swallow
// the Handle error and Record would falsely return nil after a partial
// or failed durable write.
func (a *Audit) Record(ctx context.Context, e domain.AuditEvent) error {
	a.mu.Lock()
	defer a.mu.Unlock()

	if !a.lastTS.IsZero() && !e.TS.After(a.lastTS) {
		return fmt.Errorf("%w: event %s at %s <= last %s",
			ErrOutOfOrder, e.Action, e.TS.Format(time.RFC3339Nano), a.lastTS.Format(time.RFC3339Nano))
	}

	// Spec 016 FR-015 / T052: emit `event_time` (the AuditEvent.TS at
	// which the event occurred, as stamped by the domain) alongside the
	// slog handler's own `time` (when the line was written). The two
	// timestamps drift only by the lock-acquire latency in normal
	// operation, but on a backpressured Record call they diverge — and
	// the forensic-relevant value is the domain timestamp, not the file
	// write time. Source defaults to "internal" downstream so the audit
	// log never has missing-attribution rows (FR-015 / T051).
	source := e.Source
	if source == "" {
		source = "internal"
	}
	rec := slog.NewRecord(time.Now(), slog.LevelInfo, "audit", 0)
	rec.AddAttrs(
		slog.Time("event_time", e.TS),
		slog.String("actor", e.Actor),
		slog.String("action", e.Action.String()),
		slog.String("subject", e.Subject.String()),
		slog.String("decision", e.Decision),
		slog.String("detail", e.Detail),
		slog.String("source", source),
	)
	if err := a.handler.Handle(ctx, rec); err != nil {
		return fmt.Errorf("slogaudit: durable write failed: %w", err)
	}
	a.lastTS = e.TS
	return nil
}

// Close closes the underlying file.
func (a *Audit) Close() error {
	return a.file.Close()
}
